resources:
  repositories:
  - repository: XG_Github
    type: github
    endpoint: TheRealXG
    name: therealxg/Calculator
    ref: build_container

pool:
  name: Ubuntu 20.10 VM
steps:
- checkout: XG_Github
- checkout: git://Hardware Emulation/RTEMS@refs/tags/realview_pbx_a9_qemu

- task: DockerInstaller@0
  displayName: 'Install Docker 17.09.0-ce'

- task: Docker@2
  displayName: login
  inputs:
    containerRegistry: dockerhub-realxg
    command: login

- script: |
   cd $(Build.SourcesDirectory)/Calculator
   curl 'https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip' --output build-wrapper.zip
   unzip -o build-wrapper.zip
   curl 'https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.4.0.2170-linux.zip' --output sonar.zip
   unzip -o sonar.zip -d sonar
   cd sonar
   cd */.
   mv * ../
  displayName: 'Sonarcloud Build Wrapper and Scanner Setup'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonar'
    organization: 'therealxg'
    scannerMode: 'CLI'
    configMode: 'file'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonar'
    organization: 'therealxg'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'TheRealXG_Calculator'
    cliProjectName: 'Calculator'
    cliProjectVersion: '1.1'
    cliSources: 'man/,gen/'
    extraProperties: |
      # Additional properties that will be passed to the scanner, 
      # Put one key=value per line, example:
      # sonar.exclusions=**/*.bin
      sonar.cfamily.build-wrapper-output=build_wrapper_output_directory
      sonar.sourceEncoding=UTF-8
      sonar.cfamily.cache.enabled=false
      sonar.cfamily.threads=2
      sonar.projectBaseDir=$(Build.SourcesDirectory)/Calculator

- script: |
   echo "starting" >> $(Build.SourcesDirectory)/log.txt
   docker pull therealxg/azure_pipeline:build_app
   docker run --user $(id -u):$(id -g) --rm -e SRC_VOL=$(Build.SourcesDirectory)/Calculator -e RTEMS_PATH=$(Build.SourcesDirectory)/RTEMS -v $(Build.SourcesDirectory)/RTEMS:$(Build.SourcesDirectory)/RTEMS -v $(Build.SourcesDirectory)/Calculator:$(Build.SourcesDirectory)/Calculator therealxg/azure_pipeline:build_app
   cat $(Build.SourcesDirectory)/log.txt
  displayName: 'Launch Docker Build Container'

- task: SonarCloudAnalyze@1
